# Generated by Django 5.2.7 on 2025-12-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="Ключ подтверждения"),
        ),
    ]
