# Generated by Django 5.2.7 on 2025-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_avatar_remove_user_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер"), ("admin", "Администратор")],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
